defmodule LaliaBema.Repo.Migrations.AddPhase2Resources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scope_tasks_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :text, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:scope_tasks, primary_key: false) do
      add :slug, :text, null: false, primary_key: true
    end

    alter table(:scope_tasks_versions) do
      modify :version_source_id,
             references(:scope_tasks,
               column: :slug,
               name: "scope_tasks_versions_version_source_id_fkey",
               type: :text,
               prefix: "public"
             )
    end

    alter table(:scope_tasks) do
      add :title, :text
      add :description, :text
      add :owner, :text
      add :project, :text
      add :published_at, :utc_datetime_usec
      add :claimed_at, :utc_datetime_usec
      add :ready_at, :utc_datetime_usec
      add :merged_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "published"
    end

    create table(:scope_rooms, primary_key: false) do
      add :name, :text, null: false, primary_key: true
      add :description, :text
      add :created_at, :utc_datetime_usec
      add :created_by, :text
      add :archived?, :boolean, default: false
      add :member_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:scope_messages_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:scope_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:scope_messages_versions) do
      modify :version_source_id,
             references(:scope_messages,
               column: :id,
               name: "scope_messages_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:scope_messages) do
      add :kind, :text, null: false
      add :target, :text, null: false
      add :from, :text, null: false
      add :seq, :bigint, null: false
      add :body, :text
      add :posted_at, :utc_datetime_usec
      add :path, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:scope_messages, [:kind, :target, :seq, :from],
             name: "scope_messages_kind_target_seq_from_index"
           )

    create table(:scope_agents, primary_key: false) do
      add :agent_id, :text, null: false, primary_key: true
      add :name, :text, null: false
      add :project, :text
      add :branch, :text
      add :harness, :text
      add :registered_at, :utc_datetime_usec
      add :last_seen_at, :utc_datetime_usec
      add :lease_expires_at, :utc_datetime_usec
      add :repo_root, :text
      add :pubkey, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:scope_agents)

    drop_if_exists unique_index(:scope_messages, [:kind, :target, :seq, :from],
                     name: "scope_messages_kind_target_seq_from_index"
                   )

    alter table(:scope_messages) do
      remove :updated_at
      remove :inserted_at
      remove :path
      remove :posted_at
      remove :body
      remove :seq
      remove :from
      remove :target
      remove :kind
    end

    drop constraint(:scope_messages_versions, "scope_messages_versions_version_source_id_fkey")

    alter table(:scope_messages_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:scope_messages)

    drop table(:scope_messages_versions)

    drop table(:scope_rooms)

    alter table(:scope_tasks) do
      remove :status
      remove :updated_at
      remove :inserted_at
      remove :merged_at
      remove :ready_at
      remove :claimed_at
      remove :published_at
      remove :project
      remove :owner
      remove :description
      remove :title
    end

    drop constraint(:scope_tasks_versions, "scope_tasks_versions_version_source_id_fkey")

    alter table(:scope_tasks_versions) do
      modify :version_source_id, :text
    end

    drop table(:scope_tasks)

    drop table(:scope_tasks_versions)
  end
end
